# Generated by Django 3.1.5 on 2021-04-13 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20210413_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='externaltransfer',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='market.user'),
        ),
    ]
