# Generated by Django 3.1.5 on 2021-04-13 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20210413_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalance',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.stock'),
        ),
        migrations.AlterField(
            model_name='stockbalance',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='market.user'),
        ),
    ]
