# Generated by Django 3.1.5 on 2021-04-14 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_auto_20210413_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pending',
        ),
    ]
